---
- name: Testing andrewrothstein.butane
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'butane --version'
      ansible.builtin.command: /usr/local/bin/butane --version
      changed_when: false
      register: butane_test_output
    - name: Output of 'butane --version'
      ansible.builtin.debug:
        msg: '{{ butane_test_output.stdout }}'
