---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/butane --version
    register: butane_test_output
  - name: butane --version
    debug:
      msg: '{{ butane_test_output.stdout }}'
