---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ butane_url }} to {{ butane_exe }}...
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ butane_url }}'
    dest: '{{ butane_exe }}'
    checksum: '{{ butane_checksum }}'
    mode: '755'
- name: Linking {{ butane_link }} to {{ butane_exe }}...
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ butane_exe }}'
    dest: '{{ butane_link }}'
    state: link
